@echo off
chcp 65001 >nul
setlocal EnableExtensions
rem ==========================================================================
rem  dsh-team-panel - install the team hub as an auto-start background task
rem  (start at boot + restart automatically if it crashes)
rem
rem  Usage (MUST run as Administrator):
rem    scripts\install-autostart.cmd            use default port 7801
rem    scripts\install-autostart.cmd 7900       custom port
rem
rem  What it does:
rem    1) generates scripts\_hub-autostart.cmd with the ABSOLUTE node.exe path
rem       baked in - the scheduled task runs as SYSTEM and SYSTEM's PATH does
rem       NOT contain the node.exe from your user environment
rem    2) registers scheduled task "dsh-team-panel hub":
rem       trigger=at startup, user=SYSTEM, run level=highest, restarts on crash
rem    3) starts it once and prints status
rem
rem  Uninstall: scripts\uninstall-autostart.cmd
rem
rem  NOTE: ASCII-only on purpose - cmd.exe parses .cmd with the console
rem  codepage (GBK here) and UTF-8 Chinese text corrupts that parsing.
rem  Chinese guidance is printed by Node:  node scripts\hub-info.mjs
rem ==========================================================================
set "PORT=%~1"
if "%PORT%"=="" set "PORT=7801"

set "HERE=%~dp0"
set "ROOT=%HERE%.."
set "TASK=dsh-team-panel hub"
set "RUNNER=%HERE%_hub-autostart.cmd"
set "DATA=%ROOT%\data\team-hub-data.json"
set "HUBJS=%ROOT%\lib\team-hub.mjs"

net session >nul 2>nul
if errorlevel 1 (
  echo.
  echo [ERROR] Administrator rights required.
  echo         Right-click this file and choose "Run as administrator".
  echo.
  pause
  exit /b 1
)

rem ---- resolve the absolute node.exe path ----
set "NODE="
for /f "delims=" %%i in ('where node 2^>nul') do if not defined NODE set "NODE=%%i"
if not defined NODE if exist "D:\tools\nodejson\node.exe" set "NODE=D:\tools\nodejson\node.exe"
if not defined NODE (
  echo.
  echo [ERROR] node.exe not found. Install Node.js or add it to PATH, then retry.
  echo.
  pause
  exit /b 1
)

if not exist "%HUBJS%" (
  echo.
  echo [ERROR] Cannot find %HUBJS%
  echo.
  pause
  exit /b 1
)

echo.
echo   Port       : %PORT%
echo   node       : %NODE%
echo   Runner     : %RUNNER%
echo   Data file  : %DATA%
echo   Task name  : %TASK%
echo.

rem ---- generate the runner (absolute paths + restart loop) ----
> "%RUNNER%"  echo @echo off
>>"%RUNNER%"  echo chcp 65001 ^>nul
>>"%RUNNER%"  echo rem Generated by install-autostart.cmd - do not edit by hand.
>>"%RUNNER%"  echo :loop
>>"%RUNNER%"  echo "%NODE%" "%HUBJS%" --public --port %PORT% --data "%DATA%"
>>"%RUNNER%"  echo echo [hub] exited, restarting in 5 seconds ...
>>"%RUNNER%"  echo ping -n 6 127.0.0.1 ^>nul
>>"%RUNNER%"  echo goto loop

if not exist "%RUNNER%" (
  echo [ERROR] Failed to generate the runner. Check folder write permissions.
  pause
  exit /b 1
)

echo Registering scheduled task ^(at startup / SYSTEM / highest^) ...
schtasks /create /tn "%TASK%" /tr "\"%RUNNER%\"" /sc onstart /ru SYSTEM /rl HIGHEST /f
if errorlevel 1 (
  echo.
  echo [ERROR] schtasks failed. You can create it manually in Task Scheduler:
  echo   Action  : %RUNNER%
  echo   Trigger : At startup        Run as: SYSTEM
  echo.
  pause
  exit /b 1
)

echo Starting it once ...
schtasks /run /tn "%TASK%" >nul 2>nul
ping -n 4 127.0.0.1 >nul

echo.
echo --- Task status -------------------------------------------------------
schtasks /query /tn "%TASK%" /fo LIST 2>nul

echo --- Port check --------------------------------------------------------
netstat -ano | findstr /c:"LISTENING" | findstr /c:":%PORT% "
echo.
echo If you can see 0.0.0.0:%PORT% LISTENING above, the hub is running.
echo.
echo Next steps:
echo   * Team info in Chinese:        node scripts\hub-info.mjs
echo   * Allow inbound port:          scripts\allow-firewall.cmd %PORT%   (as Administrator)
echo   * Tailscale: install it, sign in, then re-run the task to see the 100.x address:
echo       schtasks /end /tn "%TASK%"  ^&^&  schtasks /run /tn "%TASK%"
echo   * Uninstall auto-start:        scripts\uninstall-autostart.cmd
echo.
pause
exit /b 0
